service: square-sizer 

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: asia-northeast1
  project: crypto-square-lambda
  credentials: ~/.gcloud/crypto-square-lambda-4be3131bfaa3.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  square-sizer:
    handler: http
    events:
      - http: path